using System.Collections;
using System.Collections.Generic;
using UnityEngine;

#if UNITY_EDITOR
using UnityEditor;

//! 에디터 전처리기 심볼 상수
public static partial class KCEditorDefine {
	#region 기본
	public const string DS_DEFINE_S_LIGHT_ENABLE = "LIGHT_ENABLE";
	public const string DS_DEFINE_S_SHADOW_ENABLE = "SHADOW_ENABLE";
	public const string DS_DEFINE_S_IL2CPP_ENABLE = "ENABLE_IL2CPP";
	public const string DS_DEFINE_S_EDITOR_ENABLE = "EDITOR_ENABLE";
	public const string DS_DEFINE_S_MODE_2D_ENABLE = "MODE_2D_ENABLE";
	public const string DS_DEFINE_S_MODE_CENTER_ENABLE = "MODE_CENTER_ENABLE";
	public const string DS_DEFINE_S_PORTRAIT_ENABLE = "PORTRAIT_ENABLE";
	public const string DS_DEFINE_S_SECURITY_ENABLE = "SECURITY_ENABLE";
	public const string DS_DEFINE_S_LINEAR_PIPELINE_ENABLE = "LINEAR_PIPELINE_ENABLE";
	public const string DS_DEFINE_S_ULTRA_QUALITY_LEVEL_ENABLE = "ULTRA_QUALITY_LEVEL_ENABLE";
	public const string DS_DEFINE_S_PIXEL_PERFECT_ENABLE = "PIXEL_PERFECT_ENABLE";
	public const string DS_DEFINE_S_DYNAMIC_BATCHING_ENABLE = "DYNAMIC_BATCHING_ENABLE";
	public const string DS_DEFINE_S_PHYSICS_RAYCASTER_ENABLE = "PHYSICS_RAYCASTER_ENABLE";
	public const string DS_DEFINE_S_CUSTOM_TAG_ENABLE = "CUSTOM_TAG_ENABLE";
	public const string DS_DEFINE_S_CUSTOM_CAMERA_POS_ENABLE = "CUSTOM_CAMERA_POS_ENABLE";
	public const string DS_DEFINE_S_CUSTOM_SORTING_LAYER_ENABLE = "CUSTOM_SORTING_LAYER_ENABLE";

	// 플러그인
	public const string DS_DEFINE_S_ADS_ENABLE = "ADS_ENABLE";
	public const string DS_DEFINE_S_FLURRY_ENABLE = "FLURRY_ENABLE";
	public const string DS_DEFINE_S_TENJIN_ENABLE = "TENJIN_ENABLE";
	public const string DS_DEFINE_S_FACEBOOK_ENABLE = "FACEBOOK_ENABLE";
	public const string DS_DEFINE_S_FIREBASE_ENABLE = "FIREBASE_ENABLE";
	public const string DS_DEFINE_S_GAME_CENTER_ENABLE = "GAME_CENTER_ENABLE";
	public const string DS_DEFINE_S_PURCHASE_ENABLE = "PURCHASE_ENABLE";
	public const string DS_DEFINE_S_FILE_BROWSER_ENABLE = "FILE_BROWSER_ENABLE";
	public const string DS_DEFINE_S_MSG_PACK_ENABLE = "MSG_PACK_ENABLE";
	public const string DS_DEFINE_S_UNIVERSAL_RENDER_PIPELINE_ENABLE = "UNIVERSAL_RENDER_PIPELINE_ENABLE";
	public const string DS_DEFINE_S_POST_PROCESSING_ENABLE = "UNITY_POST_PROCESSING_STACK_V2";
	public const string DS_DEFINE_S_UNITY_SERVICE_ENABLE = "UNITY_SERVICE_ENABLE";

	// 태그 관리자
	public const string DS_DEFINE_S_EXTRA_TAG_ENABLE = "EXTRA_TAG_ENABLE";
	public const string DS_DEFINE_S_EXTRA_SORTING_LAYER_ENABLE = "EXTRA_SORTING_LAYER_ENABLE";

	// 테스트 {
	public const string DS_DEFINE_S_FPS_ENABLE = "FPS_ENABLE";
	public const string DS_DEFINE_S_PROFILER_ENABLE = "PROFILER_ENABLE";

	public const string DS_DEFINE_S_AB_TEST_ENABLE = "AB_TEST_ENABLE";
	public const string DS_DEFINE_S_ADS_TEST_ENABLE = "ADS_TEST_ENABLE";
	public const string DS_DEFINE_S_ROBO_TEST_ENABLE = "ROBO_TEST_ENABLE";
	public const string DS_DEFINE_S_PLAY_TEST_ENABLE = "PLAY_TEST_ENABLE";
	public const string DS_DEFINE_S_LOGIC_TEST_ENABLE = "LOGIC_TEST_ENABLE";
	public const string DS_DEFINE_S_ANALYTICS_TEST_ENABLE = "ANALYTICS_TEST_ENABLE";

	public const string DS_DEFINE_S_AB_TEST_A_ENABLE = "AB_TEST_A_ENABLE";
	public const string DS_DEFINE_S_AB_TEST_B_ENABLE = "AB_TEST_B_ENABLE";
	public const string DS_DEFINE_S_AB_TEST_C_ENABLE = "AB_TEST_C_ENABLE";
	public const string DS_DEFINE_S_AB_TEST_D_ENABLE = "AB_TEST_D_ENABLE";
	public const string DS_DEFINE_S_AB_TEST_E_ENABLE = "AB_TEST_E_ENABLE";
	public const string DS_DEFINE_S_AB_TEST_F_ENABLE = "AB_TEST_F_ENABLE";

	public const string DS_DEFINE_S_ROBO_TEST_A_ENABLE = "ROBO_TEST_A_ENABLE";
	public const string DS_DEFINE_S_ROBO_TEST_B_ENABLE = "ROBO_TEST_B_ENABLE";
	public const string DS_DEFINE_S_ROBO_TEST_C_ENABLE = "ROBO_TEST_C_ENABLE";
	public const string DS_DEFINE_S_ROBO_TEST_D_ENABLE = "ROBO_TEST_D_ENABLE";
	public const string DS_DEFINE_S_ROBO_TEST_E_ENABLE = "ROBO_TEST_E_ENABLE";
	public const string DS_DEFINE_S_ROBO_TEST_F_ENABLE = "ROBO_TEST_F_ENABLE";

	public const string DS_DEFINE_S_LOGIC_TEST_A_ENABLE = "LOGIC_TEST_A_ENABLE";
	public const string DS_DEFINE_S_LOGIC_TEST_B_ENABLE = "LOGIC_TEST_B_ENABLE";
	public const string DS_DEFINE_S_LOGIC_TEST_C_ENABLE = "LOGIC_TEST_C_ENABLE";
	public const string DS_DEFINE_S_LOGIC_TEST_D_ENABLE = "LOGIC_TEST_D_ENABLE";
	public const string DS_DEFINE_S_LOGIC_TEST_E_ENABLE = "LOGIC_TEST_E_ENABLE";
	public const string DS_DEFINE_S_LOGIC_TEST_F_ENABLE = "LOGIC_TEST_F_ENABLE";
	// 테스트 }

	// 광원
	public const string DS_DEFINE_S_LIGHTMAP_BAKE_ENABLE = "LIGHTMAP_BAKE_ENABLE";
	public const string DS_DEFINE_S_REALTIME_LIGHTMAP_ENABLE = "REALTIME_LIGHTMAP_ENABLE";
	public const string DS_DEFINE_S_DIRECTIONAL_LIGHT_REALTIME_LIGHTMAP_BAKE_ENABLE = "DIRECTIONAL_LIGHT_REALTIME_LIGHTMAP_BAKE_ENABLE";

	// 그림자
	public const string DS_DEFINE_S_SOFT_SHADOW_ENABLE = "SOFT_SHADOW_ENABLE";

	// 렌더링 파이프라인
	public const string DS_DEFINE_S_CAMERA_STACK_ENABLE = "CAMERA_STACK_ENABLE";

	// 광고
	public const string DS_DEFINE_S_ADMOB_ENABLE = "ADMOB_ENABLE";
	public const string DS_DEFINE_S_UNITY_ADS_ENABLE = "UNITY_ADS_ENABLE";
	public const string DS_DEFINE_S_IRON_SOURCE_ENABLE = "IRON_SOURCE_ENABLE";
	public const string DS_DEFINE_S_APP_LOVIN_ENABLE = "APP_LOVIN_ENABLE";

	// 분석 {
	public const string DS_DEFINE_S_AUTO_LOG_PARAM_ENABLE = "AUTO_LOG_PARAM_ENABLE";

	public const string DS_DEFINE_S_FLURRY_ANALYTICS_ENABLE = "FLURRY_ANALYTICS_ENABLE";
	public const string DS_DEFINE_S_TENJIN_ANALYTICS_ENABLE = "TENJIN_ANALYTICS_ENABLE";
	public const string DS_DEFINE_S_FACEBOOK_ANALYTICS_ENABLE = "FACEBOOK_ANALYTICS_ENABLE";
	public const string DS_DEFINE_S_FIREBASE_ANALYTICS_ENABLE = "FIREBASE_ANALYTICS_ENABLE";
	public const string DS_DEFINE_S_UNITY_SERVICE_ANALYTICS_ENABLE = "UNITY_SERVICE_ANALYTICS_ENABLE";
	// 분석 }

	// 크래시
	public const string DS_DEFINE_S_FIREBASE_CRASHLYTICS_ENABLE = "FIREBASE_CRASHLYTICS_ENABLE";
	public const string DS_DEFINE_S_UNITY_SERVICE_CRASHLYTICS_ENABLE = "UNITY_SERVICE_CRASHLYTICS_ENABLE";

	// 파이어 베이스
	public const string DS_DEFINE_S_FIREBASE_AUTH_ENABLE = "FIREBASE_AUTH_ENABLE";
	public const string DS_DEFINE_S_FIREBASE_DATABASE_ENABLE = "FIREBASE_DATABASE_ENABLE";
	public const string DS_DEFINE_S_FIREBASE_FIRESTORE_ENABLE = "FIREBASE_FIRESTORE_ENABLE";
	public const string DS_DEFINE_S_FIREBASE_REMOTE_CONFIG_ENABLE = "FIREBASE_REMOTE_CONFIG_ENABLE";
	public const string DS_DEFINE_S_FIREBASE_MSG_ENABLE = "FIREBASE_MSG_ENABLE";

	// 결제
	public const string DS_DEFINE_S_RECEIPT_CHECK_ENABLE = "RECEIPT_CHECK_ENABLE";

	// 로그인
	public const string DS_DEFINE_S_APPLE_LOGIN_ENABLE = "APPLE_LOGIN_ENABLE";

	// 게임 센터
	public const string DS_DEFINE_S_SAVED_GAME_ENABLE = "SAVED_GAME_ENABLE";

	// 플랫폼 {
	public const string DS_DEFINE_S_MAC_PLATFORM = "MAC_PLATFORM";
	public const string DS_DEFINE_S_WINDOWS_PLATFORM = "WINDOWS_PLATFORM";

	public const string DS_DEFINE_S_GOOGLE_PLATFORM = "GOOGLE_PLATFORM";
	public const string DS_DEFINE_S_ONE_STORE_PLATFORM = "ONE_STORE_PLATFORM";
	public const string DS_DEFINE_S_GALAXY_STORE_PLATFORM = "GALAXY_STORE_PLATFORM";
	// 플랫폼 }
	
	// 윈도우즈
	public const string DS_DEFINE_S_DIRECT_3D_12_ENABLE = "DIRECT_3D_12_ENABLE";

	// 배포
	public const string DS_DEFINE_S_ADHOC_BUILD = "ADHOC_BUILD";
	public const string DS_DEFINE_S_STORE_BUILD = "STORE_BUILD";

	// 기타
	public const string DS_DEFINE_S_NEVER_USE_THIS = "NEVER_USE_THIS";
	public const string DS_DEFINE_S_STUDY_MODULE_ENABLE = "STUDY_MODULE_ENABLE";
	public const string DS_DEFINE_S_USE_CUSTOM_PROJ_OPTION = "USE_CUSTOM_PROJ_OPTION";
	public const string DS_DEFINE_S_NOT_USE_CUSTOM_PROJ_OPTION = "!USE_CUSTOM_PROJ_OPTION";
	#endregion			// 기본
}
#endif			// #if UNITY_EDITOR
